name: Push Registry

on:
  push:
    tags:
    - '*'
    branches:
    - 'main'
    paths:
    - 'Dockerfile'

jobs:
  push:
    strategy:
      matrix:
        user:
        - root
        - rust

    runs-on: ubuntu-latest

    steps:
    - name: Setup code
      uses: actions/checkout@v2

    - name: Gen tag name
      id: get_tag_name
      shell: bash -x {0}
      run: |
        tag=$(echo ${{ github.ref }} | perl -nle 'print $1 if /^refs\/(?:heads|tags)\/(.*?)$/' | tr '/' '-' | sed -e 's/main/latest/')
        if [[ ${{ matrix.user }} == "rust" ]]; then
          tag=${tag}-nonroot
        fi
        echo "::set-output name=tag::$tag"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
        registry: ghcr.io

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: watawuwu/rust:${{ steps.get_tag_name.outputs.tag }}
        build-args: |
          user=${{ matrix.user }}
