name: Tracking Update v2

# on:
#   schedule:
#   - cron:  '0 0 * * *'
on:
  push:
    branches:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./tracking-update.bash

